
spring:
   
  application:
    name: 'worldgbp'
  datasource:
    driverClassName: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5432/worldgbp
    username: postgres
  jpa:
    properties:
      hibernate:
         temp:
            use_jdbc_metadata_defaults: false
         jdbc:
            lob:
               non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
                
  flyway:
    password: postgres
    url: jdbc:postgresql://localhost:5432/worldgbp
    user: postgres


