spring:
  application:
    name: OtherHWRestApi
  thymeleaf:
    cache: false
    suffix: .html
    
  datasource:
    driverClassName: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5432/otherhwrestapi
    username: postgres
  jpa:
    properties:
      hibernate:
         temp:
            use_jdbc_metadata_defaults: false
         jdbc:
            lob:
               non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
              
  flyway:
    url: jdbc:postgresql://localhost:5432/otherhwrestapi
    user: postgres
    password: postgres
